### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Krout0n** [justinmeiners/lc3-vm#25]
Hi there! Thank you for your great work!
BTW, I've noticed a little typo. If it is, can I submit PR?
>  it can understand a machine language which you can you can use to program it.
https://github.com/justinmeiners/lc3-vm/blob/master/index.lit#L41

**Comment by justinmeiners** [comment]
Yes! Thank you. A PR would be welcome, but if you don't get around to it I will fix it next time.

**Comment by Krout0n** [comment]
I've found another. Should  this`32` be `31`, right?
>  For example, -1 stored in 5 bits is `1 1111`. If we just extended it with 0's, this is `0000 0000 0001 1111` which is equal to 32!
> https://github.com/justinmeiners/lc3-vm/blob/master/index.lit#L331

**Comment by rpendleton** [comment]
You're right. That should be 31 instead of 32.
