### ISSUE TITLE
Wow thank you so much!

### ISSUE THREAD

**Issue by howtomakeaturn** [justinmeiners/lc3-vm#28]
Wow this tutorial is really amazing & helpful!

I wanna learn some basic virtualization technology principles and found your tutorial!

It's really great!

Just wanna open the issue to say thank you! 👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by justinmeiners** [comment]
Glad you enjoyed it! Sorry I didn't see this eariler!
